apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-resource-blacklist
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*' ## it means we are allowed to use any kinds of clusterscoped resources
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: 'ServiceAccount' ## it means we are NOT allowd to use 'serviceaccount' namespacescoped resource
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
