apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
              directory:
                exclude: 'service.yml'
          #      include: '{serviceaccount.yml,service.yml}'
          #      recurse: true
    path: v03-argocd-applications/directoryOfmanifests
    repoURL: https://github.com/fallahizahra123/argocd-tutorial.git
    targetRevision: main
