apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
          #    helm:
          #      releaseName: application-from-helm
          #      parameters:
          #        - name: "replicaCount"
          #          value: "3"
          #      valueFiles:
          #        - custom-values.yaml
    path: v03-argocd-applications/helm/nginx
    repoURL: https://github.com/fallahizahra123/argocd-tutorial.git
    targetRevision: main
