apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-generator
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: argocd.argoproj.io/kubernetes-version # the label argocd.argoproj.io/auto-label-cluster-info needs to be set to true on the cluster secret.
            operator: In
            values:
              - "1.28"
              - "1.31"
  template:
    metadata:
      name: '{{name}}-application'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: v03-argocd-applications/helm/nginx
      destination:
        server: '{{server}}'
        namespace: prod
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
