apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo-secret
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mohammadll/argo-tutorial.git
  username: argocd-privare-repo
  password: CHANGE_ME_WITH_TOKEN
