apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-repo-secret
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:mohammadll/argo-tutorial.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    .........................................
    -----END OPENSSH PRIVATE KEY-----
