apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-application
  namespace: argocd
spec:
  destination:
    namespace: argo-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v17-combining-argo-tools/argo-rollouts
    repoURL: https://github.com/devopshobbies/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
