apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automated-application
spec:
  destination:
    namespace: automated-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v03-argocd-applications/directoryOfmanifests
    repoURL: https://github.com/devopshobbies/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated: {}
